---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ecs-infra
  namespace: default
spec:
  interval: 1m
  url: https://github.com/chan0536/ECSWorkshop.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ecs-apps
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: ecs-infra
  path: ./simple
  prune: true
  timeout: 1m
  patches:
    - patch: |
        - op: replace
          path: /spec/className
          value: best-effort-xsmall
      target:
        kind: VirtualMachine
        name: linux-vm
---
